### PR TITLE
Make variants deletion more efficient

### LINKED ISSUE #432: Make variants deletion more efficient
Currently variants are being deleted by comparing the provider data with the existing feed table data in a php loop. 

  This needs to be replaced by a more efficient alternative.

### PR DESCRIPTION
**Pull request by bricht**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/catalog-storefront/issues/432

### Code Review Checklist (*)

- [ ] Story AC is completed
- [ ] proposed changes correspond to [Magento Technical Vision](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)
- [ ] new or changed code is covered with web-api/integration tests (if applicable)
- [ ] no backward incompatible changes

### CODE REVIEW

**Comment by bricht** [comment]
@magento run all tests

**Comment by bricht** [comment]
@magento run Static Tests

**Comment by bricht** [comment]
@magento run all tests

**Comment by bricht** [comment]
@magento run all tests

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Pull request merged**
