### PR TITLE
Remove dynamic tables creation

### LINKED ISSUE #240: "CreateDynamic" tables issue for integration tests
Web-Api and Integration tests execution takes to much time (especially with enabled Inventory modules)

Current approach \Magento\TestFramework\Application::createDynamicTables running each test execution (even more than one time for one test).

The root cause of the issue - creating tables inside a transaction (which added by test framework for isolation) and using them during the test

The proposed way to fix:
* if possible to run code before isolation transaction start:
** Remove [overridden TestFramework/Application.php|https://github.com/magento/commerce-data-export/blob/main/dev/tests/integration/framework/Magento/TestFramework/Application.php] 
** trigger table creation for specific tests
* if not possible:
** avoid run table creation for each test, run only before start test suite
** add overridden class (if no other option) to section in the main README.md file and provide explanation of the reason why the class was overwritten

### PR DESCRIPTION
**Pull request by skovalenk**
### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/catalog-storefront/issues/240

### Code Review Checklist (*)

- [ ] Story AC is completed
- [ ] proposed changes correspond to [Magento Technical Vision](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)
- [ ] new or changed code is covered with web-api/integration tests (if applicable)
- [ ] no backward incompatible changes

### CODE REVIEW

**Comment by skovalenk** [comment]
@magento run all tests

**Comment by skovalenk** [comment]
Issue: https://github.com/magento/catalog-storefront/issues/240

**Comment by skovalenk** [comment]
@magento run all tests

**Comment by mslabko** [comment]
how this fix problem if related tests are red?

**Pull request closed without merging**
