### PR TITLE
27 product variants

### LINKED ISSUE #431: ProductVariants Indexer Fix
The product variants indexing process is inefficient, since it depends on catalog_product_category.
Apply changes in https://github.com/magento/commerce-data-export/pull/11 
Fix the faulty plugin so the indexer runs as expected on ee.

1. Removed reliance on generic product index in mview.xml and index.xml
2. Added some queries and plugins to make the indexing more specific and added a workaround for the disfunctional mview, 
    by querying changes manually and adding to ids to the indexer_cl table in a CommitCallback.

### PR DESCRIPTION
**Pull request by RuslanKostiv1**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/catalog-storefront/issues/431

### Code Review Checklist (*)

See detailed [checklist](https://github.com/magento/catalog-storefront/blob/develop/dev/docs/projectAgreements/Code-Review-checklist.md)

- [ ] Story AC is completed
- [ ] proposed changes correspond to [Magento Technical Vision](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)
- [ ] new or changed code is covered with web-api/integration tests (if applicable)
  - expected results in test verified with data from fixture
- [ ] no backward incompatible changes
- [ ] Export API (et_schema.xml) and SF API schemas (proto schema) are reflected in the codebase
  - prerequisite: story branch created with all needed generated classes according to proposes schema-changes
  - DTO classes do not contain any manual changes (Magento\CatalogExportApi\*, Magento\CatalogStorefrontApi\*)
- [ ] Class usage: magento/catalog-storefront repo don't use directly classes from magento/saas-export repo and vise-verse
  - Check composer.json dependencies
- [ ] Legacy code is deleted
  - Any Data Providers present in Connector part  (Magento\CatalogStorefrontConnector, Magento\*Extractor modules)
  - And Data Providers from Export API (magento/saas-export repo) that is not relevant anymore
  - Any DTO for Export API/SF API which does not reflect current schema: et_schema, proto schema
  - Any “mapper” on Message Broker (between Export API and SF API)
    - if mapper still needed, verify fields used in mapping, remove not relevant fields

### CODE REVIEW

**Comment by bricht** [comment]
@magento run all tests

**Comment by bricht** [comment]
@magento run WebAPI tests

**Comment by bricht** [comment]
@magento run WebAPI Tests

**Comment by bricht** [comment]
@magento run Static Tests

**Comment by bricht** [comment]
@magento run all tests

**Comment by bricht** [comment]
@magento run WebAPI Tests

**Comment by bricht** [comment]
@magento run Static Tests

**Comment by bricht** [comment]
@magento run WebAPI Tests

**Comment by bricht** [comment]
@magento run WebAPI Tests

**Comment by bricht** [comment]
@magento run WebAPI Tests

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Comment by RuslanKostiv1** [comment]
@magento import pr to magento-commerce/commerce-data-export

**Comment by magento-engcom-team** [comment]
@RuslanKostiv1 the pull request successfully imported.

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Comment by bricht** [comment]
@magento run all tests

**Comment by bricht** [comment]
@magento run WebAPI tests

**Comment by bricht** [comment]
@magento run WebAPI Tests

**Comment by bricht** [comment]
@magento run all tests

**Pull request merged**
