### PR TITLE
Reindex variants by child ids

### LINKED ISSUE #437: Improve variants reindexation process.
**Current process:**
Currently the product variant indexer recieves parent product id as input.
The indexer retrieves all the variants of that product from the various variant providers (only configurable implemented so far), no matter what was updated.

The indexer sends out:
List of outdated variant ids to be deleted from catalog storefront storage.
List of variant ids to be imported in catalog storefront storage.

**Issues with current approach:**
1. We reindex all the product variants every time a single option is updated/deleted/added.
2. The indexer is currently launched by plugins which is not particularly efficient. Mview doesnt work on catalog_product_relation, because https://stackoverflow.com/questions/26328570/on-delete-cascade-not-firing-trigger ,
so plugins are used to add updated product ids to catalog_data_exporter_product_variants_cl.

### PR DESCRIPTION
**Pull request by bricht**
### Description (*)
Makes reindexation more efficient by running it by variant child product ids.
Incorporates changes from 
https://github.com/magento/commerce-data-export/pull/11
and 
https://github.com/magento/commerce-data-export/pull/12

### Fixed Issues (if relevant)

1. Fixes magento/catalog-storefront#437

### Code Review Checklist (*)

- [ ] Story AC is completed
- [ ] proposed changes correspond to [Magento Technical Vision](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)
- [ ] new or changed code is covered with web-api/integration tests (if applicable)
- [ ] no backward incompatible changes

### CODE REVIEW

**Comment by bricht** [comment]
@magento run all tests

**Comment by bricht** [comment]
@magento run all tests

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Comment by RuslanKostiv1** [comment]
@magento run Static Tests

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Comment by RuslanKostiv1** [comment]
@magento export issue to https://github.com/magento-commerce/commerce-data-export

**Comment by RuslanKostiv1** [comment]
@magento import pr to magento-commerce/commerce-data-export

**Comment by magento-engcom-team** [comment]
@RuslanKostiv1 the pull request successfully imported.

**Pull request merged**
